### PR TITLE
General fixes

### PR DESCRIPTION
**Pull request by westbrookdaniel**
Did a bunch of changes including
- Fixed dropdown and added header
- Added hero video
- Improved data collection methods for major page
- Added all students page

### CODE REVIEW

**Comment by westbrookdaniel** [comment]
@FrancisVillarba I added `majorsComputed.js` in `_data`. Does this interfere / will it be deleted by how we get new data?

**Comment by westbrookdaniel** [comment]
All student pages are working fine locally but break in staging

**Comment by FrancisVillarbaLegacy** [comment]
@westbrookdaniel great news, majorsComputed.js will not conflict, nor will it be removed / interfered with when we pull in new data from my script :)

**Review by FrancisVillarbaLegacy — APPROVED** [review]
Aside from the issue pointed out (by you), about the weirdness with the student page when linked, the rest looks super solid and awesome! 

Epic frontend work @westbrookdaniel !

**Pull request merged**
