### PR TITLE
Student data system

### LINKED ISSUE #18: Student Data System
Setting up the system for gathering student data and getting it onto the pages. 
Possibly an API?

Discuss before implementing

### PR DESCRIPTION
**Pull request by FrancisVillarbaLegacy**
Currently a draft **DO NOT MERGE**

### CODE REVIEW

**Comment by FrancisVillarbaLegacy** [comment]
[Backend Student Data System](https://trello.com/c/XRtO5sB2/33-backend-student-data-system)

**Comment by FrancisVillarbaLegacy** [comment]
Screen Shot 2020-10-14 at 4 13 56 pm
So far, console output is working as expected for pulling data -- Will soon be working on actually saving the data obtained from the database as a file in _data for eleventy

**Comment by FrancisVillarbaLegacy** [comment]
[Backend Student Data System V2](https://trello.com/c/af4aqTY2/36-backend-student-data-system-v2)

**Comment by FrancisVillarbaLegacy** [comment]
Re-marked as draft as we need to test this fully before pulling into staging

**Review by westbrookdaniel — APPROVED** [review]

**Pull request merged**
