### PR TITLE
adding student listing page

### LINKED ISSUE #15: Student Page (Listing)
Develop the basic outline for the student page including fully responsive.

Based on the wireframes pinned in the coding chat.

Don't worry about implementing complex searching or functionality.

### PR DESCRIPTION
**Pull request by Berry-James**

### CODE REVIEW

**Comment by FrancisVillarbaLegacy** [comment]
image

Just tried this preview deployment, it appears that the navigation bar added by @westbrookdaniel from a previous commit to staging is missing.

Also, Unable to preview the student page as there is no link due to the lack of navigation bar

@Berry-James have you tried pulling the latest staging and merging with your changes on your branch?
Current staging branch is on this URL https://2020-curtin-dpd-gradshow-staging.francisvillarba.vercel.app/ for reference

Cheers!
- Francis Villarba

**Comment by FrancisVillarbaLegacy** [comment]
Converted this merge commit to draft due to missing content vs. the current staging site

**Comment by westbrookdaniel** [comment]
@Berry-James Merge the branch student-listing-navbar into this branch so it's in the same PR 😄

**Comment by Berry-James** [comment]
@westbrookdaniel done, sorry I'm not very good at this.  It should work this time if you refresh the page once you're on the listing page. 

I know it's not the right way to do it, but I'm just running two scripts from the 'Student' component I made to generate the 'listings' and the 'Majors filter' via index.js (i.e. they run regardless of the current page).

**Comment by FrancisVillarbaLegacy** [comment]
No need to apologise @Berry-James :D Take this as a good learning experience! I'll have a snoop around and test it when I have the chance!

Cheers!
Francis Villarba

**Comment by FrancisVillarbaLegacy** [comment]
Screen Shot 2020-10-16 at 7 15 12 pm
So far, a quick visual inspection checks out, refresh needs to be done to list it, as you have stated earlier, I'll check out your branch as soon as I have the chance 😁

**Comment by Berry-James** [comment]
@FrancisVillarba Thanks, I appreciate your patience. 👍 I've learnt a lot being involved with this!

**Comment by westbrookdaniel** [comment]
@Berry-James We should also remove any usage of .innerHTML and use .innerText instead for security purposes 😄

**Comment by westbrookdaniel** [comment]
Also index.js is the entry point that runs on every page so change it (using swups events) to only run on the home page

**Comment by Berry-James** [comment]
Should be working now, thanks @westbrookdaniel.  Also updated all instances of .innerHTML to .innerText as requested.

**Comment by FrancisVillarbaLegacy** [comment]
**Comments**
Looks good on my end :D Well done @Berry-James!
Also, thanks @westbrookdaniel for giving @Berry-James pointers 👍 

**Actions**
- Change from draft status to standard branch
- Awaiting double check review from @westbrookdaniel to complete pull

**Review by westbrookdaniel — APPROVED** [review]

**Pull request merged**
